version: "3"

services:
  gitea_db:
    image: postgres:alpine
    container_name: gitea_db
    environment:
      - TZ=Japan
      #- POSTGRES_PASSWORD=password123
      # Settings for Gitea
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    restart: always
    volumes:
      - ./gitea_db:/var/lib/postgresql/data

  # Gitea : Git Server
  gitea:
    image: gitea/gitea:1.16.8
    container_name: gitea_app
    environment:
      - TZ=Japan
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=10022
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - 3020:3000
      - 10022:10022
    depends_on:
      - gitea_db

  # Sonarqube : static analytics
  sonar_db:
    image: postgres:alpine
    container_name: sonar_db
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      # - POSTGRES_DB=sonar
    volumes:
      - sonarqube_postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:9.4.0-community
    container_name: sonar_app
    depends_on:
      - sonar_db
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_JDBC_URL=jdbc:postgresql://sonar_db:5432/sonar
    ports:
      - 9000:9000
    restart: always
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  # Jenkins
  ci-server:
    image: jenkins/jenkins:2.349-jdk11
    container_name: jenkins_app
    ports:
      - 3080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Japan

    restart: always
  # Docker Repository
  docker-repo:
    image: registry:2.3.0
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registory:/var/lib/registry
    restart: always

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_postgresql_data:
