version: "3"

services:
  # MySQL
  gitea_db:
    image: mysql:8.0.29
    container_name: gitea_db
    environment:
      - TZ=Japan
      - MYSQL_ROOT_PASSWORD=password123
      # Settings for Gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    restart: always
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf/:/etc/mysql/conf.d

  # Gitea : Git Server
  gitea:
    image: gitea/gitea:1.16.8
    container_name: gitea_app
    environment:
      - TZ=Japan
      - USER_UID=1000
      - USER_GID=1000
      - SSH_PORT=10022
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - 3020:3000
      - 10022:10022
    depends_on:
      - gitea_db

  # Sonarqube : static analytics
  sonar_db:
    image: postgres:alpine
    container_name: sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:8.2-community
    container_name: sonar_app
    depends_on:
      - sonar_db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db/sonar
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - ./extensions:/opt/sonarqube/extensions
  
  # Drone CI : CI/CD tool
  ci-server:
    image: jenkins:2.60.3
    container_name: jenkins_app
    ports:
      - 3080:8080
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - TZ=Japan

    restart: always
  # Docker Repository
  docker-repo:
    image: registry:2.3.0
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registory:/var/lib/registry
    restart: always

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_postgresql_data:
